config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Home', 'action' => 'index', 'index']);
    $routes->connect('/admin/categories/*', ['controller' => 'Categories', 'action' => 'add']);
    $routes->connect('/admin/listings/add', ['controller' => 'Listings', 'action' => 'add']);
    $routes->connect('/admin/listings/view', ['controller' => 'Listings', 'action' => 'view']);
    $routes->connect('/admin/listings/edit/:id', ['controller' => 'Listings', 'action' => 'edit']);
    
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    //$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/BusinessCategoriesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\BusinessCategory;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * BusinessCategories Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Bcs
 * @property \Cake\ORM\Association\BelongsTo $Businesses
 * @property \Cake\ORM\Association\BelongsTo $Categories
 */
class BusinessCategoriesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('business_categories');
        $this->displayField('bc_id');
        $this->primaryKey('bc_id');

//        $this->belongsTo('Bcs', [
//            'foreignKey' => 'bc_id',
//            'joinType' => 'INNER'
//        ]);
        $this->belongsTo('Businesses', [
            'foreignKey' => 'business_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
//        $rules->add($rules->existsIn(['bc_id'], 'Bcs'));
        $rules->add($rules->existsIn(['business_id'], 'Businesses'));
        $rules->add($rules->existsIn(['category_id'], 'Categories'));
        return $rules;
    }
}

src/Controller/ListingsController.php
<?php
namespace App\Controller;
use Cake\ORM\TableRegistry;

class ListingsController extends AppController{
    
    public function initialize() {
        parent::initialize();
        $this->viewBuilder()->layout('custom_admin');
        $all_categories = TableRegistry::get('Categories')->find('all')->toArray();
        $this->set("alert", "");
        $this->set("all_categories", $all_categories);
    }
    
    public function add(){
        $this->set("page_title", "Add a new Business");
        if($this->request->is('post')){
            $bizTable = TableRegistry::get('Businesses');
            $bizEntity = $bizTable->newEntity();
            $bizEntity->set("name", strtoupper($this->request->data['business_name']));
            $bizEntity->set("description", $this->request->data['business_description']);
            $bizEntity->set("website", $this->request->data['business_website']);
            $bizEntity->set("email", $this->request->data['business_email']);
            $bizEntity->set("phone", $this->request->data['business_telephone']);
            $bizEntity->set("address", $this->request->data['business_address']);
            $array_of_categories_picked = $this->request->data['categories'];
            if($bizTable->save($bizEntity)){
                $inserted_id = $bizEntity->get("b_id");
                $this->saveToBizCategoryTable($inserted_id, $array_of_categories_picked);
                $this->set("alert", "<p class='alert alert-success'>Added Successfully</p>");
            }
            else{
                $this->set("alert", "<p class='alert alert-danger'>Business not added / Duplicate</p>");
            }
        }
        $this->set("job", "Add a new Business for Listing");
        $this->set("business_name", "");
        $this->set("business_description", "");
        $this->set("business_address", "");
        $this->set("business_email", "");
        $this->set("business_telephone", "");
        $this->set("business_website", "");
        $this->set("list_of_categories", array());
        $this->set("task", "Add");
    }
    
    
    public function view(){
        if(isset($this->request->query['delete'])){
            $idToDelete = $this->request->query['delete'];
            $bizTable = TableRegistry::get('Businesses');
            $bizTable->deleteAll(['b_id'=>$idToDelete]);
            $bizCategoryTable = TableRegistry::get('BusinessCategories');
            $bizCategoryTable->deleteAll(['business_id'=>$idToDelete]);
        }
        $this->set("page_title", "View and Manage all Business");
        $bussiness_table = TableRegistry::get('Businesses');
        $query = $bussiness_table->find('all')
                ->select(['name', 'v', 'b_id']);
        $this->set('query', $query);
    }
    
    public function edit(){
        $this->set("page_title", "Edit Business");
        $bussiness_table = TableRegistry::get('Businesses');
        $bizId = $this->request->params['id'];
        if($this->request->is('post')){
            $bizEntity = $bussiness_table->get($bizId);
            $bizEntity->set("name", strtoupper($this->request->data['business_name']));
            $bizEntity->set("description", $this->request->data['business_description']);
            $bizEntity->set("website", $this->request->data['business_website']);
            $bizEntity->set("email", $this->request->data['business_email']);
            $bizEntity->set("phone", $this->request->data['business_telephone']);
            $bizEntity->set("address", $this->request->data['business_address']);
            $array_of_categories_picked = $this->request->data['categories'];
            if($bussiness_table->save($bizEntity)){
                $bizCategoryTable = TableRegistry::get('BusinessCategories');
                $bizCategoryTable->deleteAll(['business_id'=>$bizId]);
                $this->saveToBizCategoryTable($bizId, $array_of_categories_picked);
                $this->set("alert", "<p class='alert alert-success'>Update Successfully</p>");
            }
            else{
                $this->set("alert", "<p class='alert alert-danger'>Update Filed / Duplicate</p>");
            }
        }
        
        $query = $bussiness_table->find('all')->select(['categories.c_id', 'name', 'description',
                'website', 'email', 'phone', 'address'])
                    ->leftJoin('business_categories', 'businesses.b_id = business_categories.business_id')
                    ->leftJoin('categories', 'business_categories.category_id = categories.c_id')
                ->where(['b_id'=>  $bizId]);
        $business_name = "";
        $business_description = "";
        $business_address = "";
        $business_email = "";
        $business_telephone = "";
        $business_website = "";
        $categories_ids = array();
        foreach ($query as $val){
            $business_name = empty($val->name)?$business_name:$val->name;
            $business_description = empty($val->description)?$business_description:$val->description;
            $business_address = empty($val->address)?$business_address:$val->address;
            $business_email = empty($val->email)?$business_email:$val->email;
            $business_telephone = empty($val->phone)?$business_telephone:$val->phone;
            $business_website = empty($val->website)?$business_website:$val->website;
            if($val->categories['c_id'] != null){
                array_push($categories_ids, $val->categories['c_id']);
            }
        }
        $this->set("business_name", $business_name);
        $this->set("business_description", $business_description);
        $this->set("business_address", $business_address);
        $this->set("business_email", $business_email);
        $this->set("business_telephone", $business_telephone);
        $this->set("business_website", $business_website);
        $this->set("list_of_categories", $categories_ids);
        $this->set("job", "Edit Listing of : ".$business_name);
        $this->set("task", "Update");
        $this->viewBuilder()->template('add');
    }
    
    private function saveToBizCategoryTable($id, $array_picked){
        $bizCategoryTable = TableRegistry::get('BusinessCategories');
        foreach($array_picked as $cat_picked){
            $ent = $bizCategoryTable->newEntity();
            $ent->set("category_id", intval($cat_picked));
            $ent->set("business_id", $id);
            $bizCategoryTable->save($ent);
        }
    }
}

src/Template/Listings/add.ctp
<h3><?= $job ?></h3>
<?= $alert; ?>
<form method="post" class="col-sm-9">
    <div class="form-group">
        <input type="text" name="business_name" class="form-control" 
               value="<?= $business_name ?>" placeholder="Enter business name" required=""/>
    </div>
    <div class="form-group">
        <textarea class="form-control" name="business_address" 
                  placeholder="Enter business full address" required=""><?= $business_address ?></textarea>
    </div>
    <div class="form-group">
        <input type="text" name="business_email" class="form-control" 
                value="<?= $business_email ?>" placeholder="Enter business email" required=""/>
    </div>
    <div class="form-group">
        <input type="text" name="business_telephone" class="form-control" 
               value="<?= $business_telephone ?>" placeholder="Enter business telephone" required=""/>
    </div>
    <div class="form-group">
        <input type="text" name="business_website" class="form-control" 
               value="<?= $business_website ?>" placeholder="Enter business website" required=""/>
    </div>
    <div class="form-group">
        <textarea class="form-control" name="business_description" 
                  placeholder="Enter business description" required=""><?= $business_description ?></textarea>
    </div>
    <div class="form-group">
        <label>Select Categories Business Belongs to:</label><br />
        <?php
            foreach($all_categories as $cat){
                $checked = "";
                if(in_array($cat->c_id, $list_of_categories)){
                    $checked = "checked";
                }
        ?>
                <div class="checkbox">
                    <label>
                        <input type='checkbox' name='categories[]' value='<?= $cat->c_id ?>' <?= $checked ?>>
                        <?= $cat->category ?>
                        <i class="input-helper"></i>
                    </label>
                </div>
        <?php
            }
        ?>
    </div>
    
    <input type="submit" name="add_cat" class="btn btn-primary" value="<?= $task ?> Business" />
</form>

src/Template/Listings/view.ctp
<h3>View Listings</h3>
<?= $alert; ?>
<table class="col-sm-12">
    <thead>
    <th>S/N</th>
    <th>Business Name</th>
    <th>View Counts</th>
    <th>Edit</th>
    <th>Delete</th>
    </thead>
    <tbody>
        <?php 
        $sn = 1;
            foreach($query as $one){
        ?>
        <tr>
            <td><?= $sn ?></td>
            <td><?= $one->name ?></td>
            <td><?= $one->v ?></td>
            <td><a href="/admin/listings/edit/<?= $one->b_id ?>">edit</a></td>
            <td><a class="text-danger" href="/admin/listings/view/?delete=<?= $one->b_id ?>">delete</a></td>
        </tr>
        <?php
        $sn++;
            }
        ?>
    </tbody>
</table>